-- ============================================================
--  PREDICTA26 — Turso Schema
--  Place this file at: db/schema.sql
--  The server runs this automatically on startup.
-- ============================================================


-- ------------------------------------------------------------
--  users
--  One row per registered participant.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            TEXT    PRIMARY KEY,          -- UUID generated by the app
  display_name  TEXT    NOT NULL,
  email         TEXT    NOT NULL UNIQUE,
  total_points  REAL    NOT NULL DEFAULT 0,
  created_at    TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- ------------------------------------------------------------
--  winner_picks
--  Each user's current winning-team pick.
--  One active pick per user at a time (enforced by UNIQUE on user_id).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS winner_picks (
  id                  TEXT    PRIMARY KEY,
  user_id             TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  team_name           TEXT    NOT NULL,
  win_probability     REAL    NOT NULL,   -- % at time of pick  (e.g. 17.4)
  projected_points    REAL    NOT NULL,   -- payout if correct
  settled             INTEGER NOT NULL DEFAULT 0,   -- 0 = open, 1 = settled
  created_at          TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (user_id)                        -- only one active pick per user
);


-- ------------------------------------------------------------
--  points_ledger
--  Immutable record of every point award after settlement.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS points_ledger (
  id          TEXT    PRIMARY KEY,
  user_id     TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pick_id     TEXT    NOT NULL REFERENCES winner_picks(id),
  team_name   TEXT    NOT NULL,
  points      REAL    NOT NULL,
  reason      TEXT    NOT NULL DEFAULT 'winner_settlement',
  awarded_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- ------------------------------------------------------------
--  model_runs
--  One row per published snapshot from the Python model.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_runs (
  id           TEXT    PRIMARY KEY,
  source       TEXT    NOT NULL DEFAULT 'python-model',
  simulations  INTEGER NOT NULL,
  published_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);


-- ------------------------------------------------------------
--  model_team_probabilities
--  Per-team figures attached to a model run.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS model_team_probabilities (
  id                  TEXT    PRIMARY KEY,
  model_run_id        TEXT    NOT NULL REFERENCES model_runs(id) ON DELETE CASCADE,
  team_name           TEXT    NOT NULL,
  win_probability     REAL    NOT NULL,   -- % chance of winning the tournament
  final_probability   REAL,               -- % chance of reaching the final
  semi_probability    REAL,               -- % chance of reaching the semi-final
  rating              REAL,               -- Elo / power rating used in simulation
  projected_payout    REAL,               -- points a correct pick would earn now
  UNIQUE (model_run_id, team_name)
);


-- ------------------------------------------------------------
--  Indexes
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_winner_picks_user_id
  ON winner_picks (user_id);

CREATE INDEX IF NOT EXISTS idx_points_ledger_user_id
  ON points_ledger (user_id);

CREATE INDEX IF NOT EXISTS idx_model_team_probabilities_run_id
  ON model_team_probabilities (model_run_id);

CREATE INDEX IF NOT EXISTS idx_model_runs_published_at
  ON model_runs (published_at DESC);